// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PageTurners.Core.Context;

#nullable disable

namespace PageTurners.Core.Migrations
{
    [DbContext(typeof(PageTurnersContext))]
    partial class PageTurnersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b2375ead-04ae-4380-b5a0-178cd649c9bc",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "62a5ba33-da48-4c12-8efd-5f4b23daf7ff",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "2494108a-38d1-4d5c-a41a-47512a0e4ff1",
                            Name = "Reader",
                            NormalizedName = "READER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4ddff3a6-fcbe-48a2-a275-96d1641e7926",
                            RoleId = "b2375ead-04ae-4380-b5a0-178cd649c9bc"
                        },
                        new
                        {
                            UserId = "4ddff3a6-fcbe-48a2-a275-96d1641e7926",
                            RoleId = "62a5ba33-da48-4c12-8efd-5f4b23daf7ff"
                        },
                        new
                        {
                            UserId = "70080728-b8bb-4198-86cf-64b9e03df115",
                            RoleId = "62a5ba33-da48-4c12-8efd-5f4b23daf7ff"
                        },
                        new
                        {
                            UserId = "5f440aba-dd59-4f43-acb5-062dfadd7f4b",
                            RoleId = "62a5ba33-da48-4c12-8efd-5f4b23daf7ff"
                        },
                        new
                        {
                            UserId = "5f440aba-dd59-4f43-acb5-062dfadd7f4b",
                            RoleId = "b2375ead-04ae-4380-b5a0-178cd649c9bc"
                        },
                        new
                        {
                            UserId = "5f440aba-dd59-4f43-acb5-062dfadd7f4b",
                            RoleId = "2494108a-38d1-4d5c-a41a-47512a0e4ff1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PageTurners.Core.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AverageRating")
                        .HasColumnType("float");

                    b.Property<int>("DatePubl")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Роберт Грін",
                            DatePubl = 1998,
                            Desc = "Ця книга розглядає стратегії та тактики влади, використовуючи приклади з історії та сучасного бізнесу.",
                            Edition = "Viking Press",
                            Genre = "Психологія, бізнес",
                            Title = "Ігри влади"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Френсіс Скотт Фіцджеральд",
                            DatePubl = 1925,
                            Desc = "Цей роман розповідає історію багатого і таємничого Джей Гетсбі та його пристрасті до недосяжної коханої Дейзі.",
                            Edition = "Charles Scribner's Sons",
                            Genre = "Класика, роман",
                            Title = "Великий Гетсбі"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Анна Тодд",
                            DatePubl = 2014,
                            Desc = "Ця книга розповідає про складність переходу від підліткового життя до дорослого, з фокусом на романтичних відносинах.",
                            Edition = "Gallery Books",
                            Genre = "Роман, молодіжна література",
                            Title = "Після"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Джордж Р. Р. Мартін",
                            DatePubl = 1996,
                            Desc = "Перша книга серії `Пісня льоду і полум'я` розповідає про боротьбу різних родів за трон Залізного Трону у міфічному світі Вестерос.",
                            Edition = "Bantam Spectra",
                            Genre = "Фентезі, пригоди",
                            Title = "Гра престолів"
                        });
                });

            modelBuilder.Entity("PageTurners.Core.Entities.BookRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatePubl")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Юлія Лабурнум",
                            DatePubl = 0,
                            OwnerId = "70080728-b8bb-4198-86cf-64b9e03df115",
                            Title = "Лабіринт часу"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Андрій Землянський",
                            DatePubl = 0,
                            Desc = "Спадщина Марса - це захоплюючий науково-фантастичний роман, який перенося читача у далеке майбутнє, на таємничу і загадкову планету Марс. Автор, Андрій Землянський, розповідає історію групи вчених і дослідників, які вирушають на Марс, щоб розкрити його давні таємниці.",
                            OwnerId = "4ddff3a6-fcbe-48a2-a275-96d1641e7926",
                            Title = "Спадщина Марса"
                        });
                });

            modelBuilder.Entity("PageTurners.Core.Entities.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CommentatorId");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 3,
                            Comment = "Дуже цікава історія!",
                            CommentatorId = "4ddff3a6-fcbe-48a2-a275-96d1641e7926",
                            Date = new DateTime(2023, 12, 16, 14, 6, 45, 872, DateTimeKind.Local).AddTicks(3159)
                        },
                        new
                        {
                            Id = 2,
                            BookId = 1,
                            Comment = "Трохи нудно...",
                            CommentatorId = "70080728-b8bb-4198-86cf-64b9e03df115",
                            Date = new DateTime(2023, 12, 16, 14, 6, 45, 872, DateTimeKind.Local).AddTicks(3271)
                        });
                });

            modelBuilder.Entity("PageTurners.Core.Entities.ModeratorReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ModeratorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookRequestId");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4ddff3a6-fcbe-48a2-a275-96d1641e7926",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e4a63745-1787-4c06-a8aa-47b7e26ae47b",
                            DateOfBirth = new DateTime(2052, 12, 16, 14, 6, 45, 383, DateTimeKind.Local).AddTicks(3005),
                            Email = "admin@pageturners.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Login = "ivan123",
                            Name = "Іван Сергійович",
                            NormalizedEmail = "ADMIN@PAGETURNERS.COM",
                            NormalizedUserName = "ADMIN@PAGETURNERS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEJk2hiNWul9jB9LuWDJ4MO3YuwnBLmJ/pfhPB2KyY/xgy1XEGvtrPOvbWbe/4sapg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cff62971-7764-47bd-a43c-7f06f6d849d8",
                            TwoFactorEnabled = false,
                            UserName = "admin@pageturners.com"
                        },
                        new
                        {
                            Id = "70080728-b8bb-4198-86cf-64b9e03df115",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "94343e5d-0aa8-4b93-bf89-078c9b51c2e9",
                            DateOfBirth = new DateTime(2044, 12, 16, 14, 6, 45, 383, DateTimeKind.Local).AddTicks(3095),
                            Email = "moderator@pageturners.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Login = "daria684",
                            Name = "Дарія Петрівна",
                            NormalizedEmail = "MODERATOR@PAGETURNERS.COM",
                            NormalizedUserName = "MODERATOR@PAGETURNERS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEINrL1j9y2uCrLsAiFl8uTFeZgvRAMq0zSiz4knueaLPD5KGEjAZfYI7mX7gOR7WAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31eb6ba3-c6e3-46c8-9ee8-c32a476f9667",
                            TwoFactorEnabled = false,
                            UserName = "moderator@pageturners.com"
                        },
                        new
                        {
                            Id = "5f440aba-dd59-4f43-acb5-062dfadd7f4b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef80de08-98ed-46bc-8618-8369ea061b0a",
                            DateOfBirth = new DateTime(2044, 12, 16, 14, 6, 45, 383, DateTimeKind.Local).AddTicks(3120),
                            Email = "reader@pageturners.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Login = "anna456",
                            Name = "Анна Олександрівна",
                            NormalizedEmail = "READER@PAGETURNERS.COM",
                            NormalizedUserName = "READER@PAGETURNERS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECon8neox6Xhqs/OAMUd09m6XIyaX9gX9jkp+S6ZXOFKaz/5E05hz4atjekqnFpgBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "baef2c25-0322-4e7f-9fc5-908436478aee",
                            TwoFactorEnabled = false,
                            UserName = "reader@pageturners.com"
                        });
                });

            modelBuilder.Entity("PageTurners.Core.Entities.UserBook", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("BookId1")
                        .HasColumnType("int");

                    b.Property<int>("UserBookId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BookId");

                    b.HasIndex("BookId");

                    b.HasIndex("BookId1");

                    b.ToTable("UserBooks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PageTurners.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PageTurners.Core.Entities.BookRequest", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.User", "Owner")
                        .WithMany("BookRequests")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.Comments", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.Book", "Book")
                        .WithMany("Comment")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PageTurners.Core.Entities.User", "Commentator")
                        .WithMany("Comment")
                        .HasForeignKey("CommentatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Commentator");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.ModeratorReview", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.BookRequest", "BookRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("BookRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PageTurners.Core.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PageTurners.Core.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookRequest");

                    b.Navigation("Moderator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.Rating", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.Book", "Book")
                        .WithMany("Ratings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PageTurners.Core.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.UserBook", b =>
                {
                    b.HasOne("PageTurners.Core.Entities.Book", "Book")
                        .WithMany("UsersReadLater")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PageTurners.Core.Entities.Book", null)
                        .WithMany("UsersReadBooks")
                        .HasForeignKey("BookId1");

                    b.HasOne("PageTurners.Core.Entities.User", "User")
                        .WithMany("ToReadList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.Book", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("Ratings");

                    b.Navigation("UsersReadBooks");

                    b.Navigation("UsersReadLater");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.BookRequest", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PageTurners.Core.Entities.User", b =>
                {
                    b.Navigation("BookRequests");

                    b.Navigation("Comment");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("ToReadList");
                });
#pragma warning restore 612, 618
        }
    }
}
